-- Better-Auth schema for control-panel.
--
-- Generated by `npx @better-auth/cli generate --config src/lib/auth/server.ts`
-- (better-auth 1.5.5). The CLI emits unqualified table names; we prepend
-- a CREATE SCHEMA + SET search_path so all four tables land in auth.*
-- instead of public.*. This matches the core/auth split agreed in the spec.
--
-- The Pool in src/lib/auth/server.ts also runs `SET search_path TO auth, public`
-- on every checkout so runtime queries hit the same tables.

CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION ribbler;
SET search_path TO auth, public;

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");
